### ISSUE TITLE
result inconsistency during clustering step

### ISSUE THREAD

**Issue by juferban** [genome/sciclone#15]
Hi,

I have been testing SciClone as a solution to make clonality predictions for one of the datasets I am working with.
I noticed that if I run SciClone multiple times on the same sample data I get a prediction consistency of 90%  but then there is this 10% that produces a completely different prediction.
My test case has 212 variant of which only 22 are selected for clustering. After running with the code below I get 2 clusters predicting most of the time but in that 10% of the runs I get 4 clusters predicted.

Not sure if this is a bug, something expected or maybe a problem caused by other library but thought on reporting just in case you want to investigate. I may be able to send my test files if needed.

Thanks

```
sc = sciClone(vafs=v1,
              copyNumberCalls=cn1,
              sampleNames=names[1],
              cnCallsAreLog2 = TRUE,
              copyNumberMargins = 0.50,
              minimumDepth = 100,
              maximumCluster = 10
              )
```

My session information:
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.4 (Final)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
 [1] grid      stats4    parallel  stats     graphics  grDevices utils
 [8] datasets  methods   base

other attached packages:
 [1] sciClone_1.1.0      TeachingDemos_2.10  MKmisc_0.991
 [4] plotrix_3.6-1       RColorBrewer_1.1-2  rgl_0.95.1441
 [7] bmm_0.3.1           NORMT3_1.0-3        ggplot2_2.1.0
[10] IRanges_2.4.8       S4Vectors_0.8.11    BiocGenerics_0.16.1

loaded via a namespace (and not attached):
[1] Rcpp_0.12.4       plyr_1.8.3        gtable_0.2.0      scales_0.4.0
[5] robustbase_0.92-5 DEoptimR_1.0-4    munsell_0.4.3     colorspace_1.2-6

**Comment by chrisamiller** [comment]
Yes, this is known behavior. Ultimately, this has to do with the fact that the underlying clustering algorithms use random starting positions to begin with, then iteratively refine, so subsequent runs may return slightly different results.  The reason that you see such dramatic shifts is likely because you have so few points to cluster with.  If failure to reach the minimum depth is the reason that most points are filtered out, I'd try setting that param to something lower. (maybe 50?).  Just be aware that you're trading off some resolution when you do so. (see Figure 5 here: http://www.cell.com/cell-systems/abstract/S2405-4712(15)00113-1 )  Best of luck!

**Comment by juferban** [comment]
Hi Chris,

Thanks a lot for the quick answer and for the tips. I will give it a try and play a little bit with the parameters now knowing that the small number of variants may be the reason for the behavior.

Best regards.
