### ISSUE TITLE
Topological tumour samples

### ISSUE THREAD

**Issue by tomasellimichelle** [genome/sciclone#46]
Hi, I am trying to run 4 tumour samples from different cancer regions. I would like to know which parameters do you recommend to use. 
- The data was cleaned from possible CNAs
- The study can use all variants in the input files "minimum depth = 0"

I used this code, but cluster 1 only have 3 variants, How can I removed this cluster? Maybe the method? .. 
sc = sciClone(vafs=list(dfVAF1,dfVAF2,dfVAF3,dfVAF4),cnCallsAreLog2=FALSE,copyNumberCalls=NULL, regionsToExclude=NULL,useSexChrs=TRUE,doClusteringAlongMargins=FALSE,minimumDepth=0,sampleNames=samples,clusterMethod="bmm",doClustering=TRUE, annotation=NULL, maximumClusters=10, verbose=TRUE)

Thanks for your help, 
Michelle.

**Comment by chrisamiller** [comment]
Sorry for the slow response.  Sciclone is very much a "garbage in garbage out" kind of algorithm. If there are points/clusters that don't make any sense, it's often because they are false-positive variant calls or calls from copy-number altered regions (both of which will result in weird VAFs).  If this turns out to be the case, you can either drop them from your input list or use the "exclude" list to remove them from consideration.
