### ISSUE TITLE
Error in xtfrm.data.frame(x)

### ISSUE THREAD

**Issue by monkeyBai96** [genome/sciclone#52]
When i run sciClone function, 
sc = sciClone(vafs=vaf_list, sampleNames=sample, maximumClusters = 2)
ERROR comes:
Error in xtfrm.data.frame(x) : cannot xtfrm data frames

I'm sure my commands worked in the previous version, one year ago.
My version now: R 4.3.0 SciClone 1.1.0

**Comment by kunstner** [comment]
Hi,
I provide a fix for this issue in my repo, where I forked sciClone (https://github.com/kunstner/sciclone). You have to make sure that the dplyr package is installed because the fix uses dplyr:arrange(). Furthermore, it needs at elast R 4.1.0 because it uses the pipe operator (|>).
Hope it helps,
 Axel

**Comment by chrisamiller** [comment]
Great - thanks for hacking on it!  Would you be willing to submit the changes as a pull request, so I can incorporate them into the main package here?

**Comment by kunstner** [comment]
Done :)

**Comment by chrisamiller** [comment]
closed by commit https://github.com/genome/sciclone/commit/795d2da50bf59b46010380dd9b4f4f415fbcaa3e

Feel free to reopen if any related issues pop up!
