### ISSUE TITLE
Not mapping relapse/primary specific variants

### ISSUE THREAD

**Issue by poojitha88** [genome/sciclone#9]
Hello,
I am trying to make a 2d plot for primary versus relapse samples, but it does not plot varaitns which are specific to a particular sample, i.e not shared between the samples. I checked the cluster file and it designates varaitns with no vaf as NA instead of 0. Is there a way to chacnge this? on a normal datafram is.na would work but doesnt seem to be the case here. Could you please help? Below is the command

sc <- sciClone(vafs=list(tum,rel), sampleNames=samples, maximumClusters = 5, minimumDepth=20, verbose=1, doClusteringAlongMargins=TRUE, clusterMethod = "binomial.bmm")

sc.plot2d(sc, "Patient1.pdf")

**Comment by chrisamiller** [comment]
SciClone expects that every site in every sample has readcount and VAF information. If the VAF is zero, then that should be noted. If the site was not assayed in the other samples, it's dangerous to assume that the variant has a VAF of zero. (Just because a mutation was not detected in a sample doesn't mean that it's VAF is zero - many low-frequency variants  (< 5-10% VAF) will not be detected as somatic hits by mutation callers).

In practice, the easiest way to achieve this is to merge the mutation lists from all samples, then pull new readcounts from each sample for the entire list.

**Comment by poojitha88** [comment]
Thanks very much for the reply and suggestion. I will implement it and redo the analysis. As you pointed out the mutation caller does not give the output for positions that match the reference. Will work this out.
